//
// Agent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Agent: Codable {

    public var name: String
    public var type: String
    public var llm: Any?
    public var hasMemory: Bool?
    public var promptId: String?

    public init(name: String, type: String, llm: Any? = nil, hasMemory: Bool? = nil, promptId: String? = nil) {
        self.name = name
        self.type = type
        self.llm = llm
        self.hasMemory = hasMemory
        self.promptId = promptId
    }


}
