//
// AgentDocument.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AgentDocument: Codable {

    public var agentId: String
    public var documentId: String

    public init(agentId: String, documentId: String) {
        self.agentId = agentId
        self.documentId = documentId
    }


}
