//
// AgentTool.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AgentTool: Codable {

    public var agentId: String
    public var toolId: String

    public init(agentId: String, toolId: String) {
        self.agentId = agentId
        self.toolId = toolId
    }


}
