//
// PredictAgent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PredictAgent: Codable {

    public var input: Any
    public var hasStreaming: Bool?

    public init(input: Any, hasStreaming: Bool? = nil) {
        self.input = input
        self.hasStreaming = hasStreaming
    }

    public enum CodingKeys: String, CodingKey { 
        case input
        case hasStreaming = "has_streaming"
    }

}
