//
// Prompt.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Prompt: Codable {

    public var name: String
    public var inputVariables: [Any]
    public var template: String

    public init(name: String, inputVariables: [Any], template: String) {
        self.name = name
        self.inputVariables = inputVariables
        self.template = template
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case inputVariables = "input_variables"
        case template
    }

}
