//
// Tool.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Tool: Codable {

    public var name: String
    public var type: String
    public var _description: String
    public var authorization: Any?
    public var metadata: Any?

    public init(name: String, type: String, _description: String, authorization: Any? = nil, metadata: Any? = nil) {
        self.name = name
        self.type = type
        self._description = _description
        self.authorization = authorization
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case type
        case _description = "description"
        case authorization
        case metadata
    }

}
