//
// ValidationError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ValidationError: Codable {

    public var loc: [AnyOfValidationErrorLocItems]
    public var msg: String
    public var type: String

    public init(loc: [AnyOfValidationErrorLocItems], msg: String, type: String) {
        self.loc = loc
        self.msg = msg
        self.type = type
    }


}
